WITH TRIPS AS (
    SELECT
       
RIDE_ID,
RIDEABLE_TYPE,
DATE(TO_TIMESTAMP(STARTED_AT)) AS TRIP_DATE,
START_STATIO_ID
END_STATION_ID,
MEMBER_CSUAL AS MEMBER_CASUAL,
        DATEDIFF(second, TRY_TO_TIMESTAMP(STARTED_AT), TRY_TO_TIMESTAMP(ENDED_AT)) AS TRIP_DURATION_SECOND
    FROM {{ source('demo', 'bike') }}
    WHERE RIDE_ID != 'ride_id'
)

SELECT * FROM TRIPS